stages:
    - build
    - deploy

variables:
    IMAGE_NAME: "anav5704/hono-server"
    IMAGE_TAG: "gitlab"

build:
    stage: build

    image: docker:20.10.24

    services:
        - docker:20.10.24-dind

    variables:
        DOCKER_TLS_CERTDIR: "/certs"

    before_script:
        - apt upgrade && apt update
        - docker login -u $DOCKER_USER -p $DOCKER_PSWD

    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
    stage: deploy

    before_script:
        - chmod 400 $SSH_KEY

    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$HOST_NAME "
          docker login -u $DOCKER_USER -p $DOCKER_PSWD &&
          docker-compose -f $COMPOSE_FILE down &&
          docker-compose -f $COMPOSE_FILE pull &&
          docker-compose -f $COMPOSE_FILE up -d"
